### ISSUE TITLE
Search GUI using web-services fail

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Toolsuite/pride-inspector#45]
Search archive function: when I entered "melanoma" the list didn't change. Still, all projects were being displayed (screenshot 4). The download dialog didn't provide me with a quick option to only select "RESULT files", also, a "de-select all" button is missing. I had to manually de-select ~70 RAW files. This is not very nice. The download then didn't start and the GUI didn't show any error message. I only discovered this on the command line:

uk.ac.ebi.pride.toolsuite.gui.task.impl.AsperaDownloadTask@59360e80 failed on : com.asperasoft.faspmanager.LaunchException: Error starting transfer process: Failed to start process
com.asperasoft.faspmanager.LaunchException: Error starting transfer process: Failed to start process
    at com.asperasoft.faspmanager.Session.start(Session.java:725) ~[aspera-faspmanager-2.7.0.42750.jar:2.7.0.42750 ]
    at com.asperasoft.faspmanager.FaspManager.startTransfer(FaspManager.java:768) ~[aspera-faspmanager-2.7.0.42750.jar:2.7.0.42750 ]
    at com.asperasoft.faspmanager.FaspManager.startTransfer(FaspManager.java:736) ~[aspera-faspmanager-2.7.0.42750.jar:2.7.0.42750 ]
    at uk.ac.ebi.pride.toolsuite.gui.aspera.AsperaFileUploader.downloadFiles(AsperaFileUploader.java:180) ~[pride-inspector-2.5.0-SNAPSHOT.jar:na]
    at uk.ac.ebi.pride.toolsuite.gui.task.impl.AsperaDownloadTask.asperaUpload(AsperaDownloadTask.java:81) ~[pride-inspector-2.5.0-SNAPSHOT.jar:na]
    at uk.ac.ebi.pride.toolsuite.gui.task.impl.AsperaDownloadTask.doInBackground(AsperaDownloadTask.java:41) ~[pride-inspector-2.5.0-SNAPSHOT.jar:na]
    at uk.ac.ebi.pride.toolsuite.gui.task.impl.AsperaDownloadTask.doInBackground(AsperaDownloadTask.java:26) ~[pride-inspector-2.5.0-SNAPSHOT.jar:na]
    at javax.swing.SwingWorker$1.call(SwingWorker.java:296) ~[na:1.7.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_65]
    at javax.swing.SwingWorker.run(SwingWorker.java:335) ~[na:1.7.0_65]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_65]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_65]

**Comment by ruiwanguk** [comment]
@ypriverol  Couldn't replicate the problem with downloading and searching, please ask Johannes about his operating system details.

**Comment by ruiwanguk** [comment]
I have added a button to select/deselect all the files

**Comment by ypriverol** [comment]
+1 Issue Solved
