### ISSUE TITLE
mvn install fails with errors

### ISSUE THREAD

**Issue by wolski** [PRIDE-Toolsuite/pride-inspector#54]
just cloned the repo (master commit bf3dd55d6f2dcc8bde0b8c1d2fedb4b64c17a407) and trying to build it. mvn install does not work

PS C:\Users\wolski\prog\pride-inspector> mvn -e install
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building pride-inspector 2.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for uk.ac.ebi.pride.tools:mzdata-parser:jar:1.2.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for uk.ac.ebi.pride.jaxb:pride-jaxb:jar:1.0.13-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for uk.ac.ebi.pride.utilities:pride-utilities:jar:2.0.5-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for uk.ac.ebi.pride.toolsuite:inspector-mzgraph-browser:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for uk.ac.ebi.pride.toolsuite:inspector-quality-chart:jar:2.0.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for uk.ac.ebi.pride.toolsuite:inspector-swing-utils:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for uk.ac.ebi.pride.utilities:pride-protein-inference:jar:0.0.5-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.asperasoft:aspera-faspmanager:jar:2.7.0.42750 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.850s
[INFO] Finished at: Wed Nov 18 11:33:53 CET 2015
[INFO] Final Memory: 9M/429M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pride-inspector: Could not resolve dependencies for project uk.ac.ebi.pride.toolsuite:pride-inspector:jar:2.5.0-SNAPSHOT: The following artifacts could not be resolved: uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT, uk.ac.ebi.pride.tools:mzdata-parser:jar:1.2.2-SNAPSHOT, uk.a
c.ebi.pride.jaxb:pride-jaxb:jar:1.0.13-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-mzgraph-browser:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-quality-chart:jar:2.0.3-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-swing-utils:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pride.utilities:pride-utilities:jar:2.0.5-SNAPSHOT,
 uk.ac.ebi.pride.utilities:pride-protein-inference:jar:0.0.5-SNAPSHOT, com.asperasoft:aspera-faspmanager:jar:2.7.0.42750: Failure to find uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT in http://pride-proteome.sourceforge.net/maven2 was cached in the local repository, resolution will not be reattempted until the updat
e interval of PRIDE_SourceForge_Maven2_Repository has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project pride-inspector: Could not resolve dependencies for project uk.ac.ebi.pride.toolsuite:pride-inspector:jar:2.5.0-SNAPSHOT: The following artifacts could not be resolved: uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT, uk.ac.ebi.pr
ide.tools:mzdata-parser:jar:1.2.2-SNAPSHOT, uk.ac.ebi.pride.jaxb:pride-jaxb:jar:1.0.13-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-mzgraph-browser:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-quality-chart:jar:2.0.3-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-swing-utils:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pri
de.utilities:pride-utilities:jar:2.0.5-SNAPSHOT, uk.ac.ebi.pride.utilities:pride-protein-inference:jar:0.0.5-SNAPSHOT, com.asperasoft:aspera-faspmanager:jar:2.7.0.42750: Failure to find uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT in http://pride-proteome.sourceforge.net/maven2 was cached in the local repository, re
solution will not be reattempted until the update interval of PRIDE_SourceForge_Maven2_Repository has elapsed or updates are forced
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project uk.ac.ebi.pride.toolsuite:pride-inspector:jar:2.5.0-SNAPSHOT: The following artifacts could not be resolved: uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT, uk.ac.ebi.pride.tools:mzdata-parser:jar:1.2.2-SNAPSH
OT, uk.ac.ebi.pride.jaxb:pride-jaxb:jar:1.0.13-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-mzgraph-browser:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-quality-chart:jar:2.0.3-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-swing-utils:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pride.utilities:pride-utilities:jar:2.0.5-S
NAPSHOT, uk.ac.ebi.pride.utilities:pride-protein-inference:jar:0.0.5-SNAPSHOT, com.asperasoft:aspera-faspmanager:jar:2.7.0.42750: Failure to find uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT in http://pride-proteome.sourceforge.net/maven2 was cached in the local repository, resolution will not be reattempted until t
he update interval of PRIDE_SourceForge_Maven2_Repository has elapsed or updates are forced
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:189)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
        ... 22 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT, uk.ac.ebi.pride.tools:mzdata-parser:jar:1.2.2-SNAPSHOT, uk.ac.ebi.pride.jaxb:pride-jaxb:jar:1.0.13-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-mzgrap
h-browser:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-quality-chart:jar:2.0.3-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-swing-utils:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pride.utilities:pride-utilities:jar:2.0.5-SNAPSHOT, uk.ac.ebi.pride.utilities:pride-protein-inference:jar:0.0.5-SNAPSHOT, com.asperasoft:asper
a-faspmanager:jar:2.7.0.42750: Failure to find uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT in http://pride-proteome.sourceforge.net/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of PRIDE_SourceForge_Maven2_Repository has elapsed or updates are forced
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:183)
        ... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT, uk.ac.ebi.pride.tools:mzdata-parser:jar:1.2.2-SNAPSHOT, uk.ac.ebi.pride.jaxb:pride-jaxb:jar:1.0.13-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-mzgraph-
browser:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-quality-chart:jar:2.0.3-SNAPSHOT, uk.ac.ebi.pride.toolsuite:inspector-swing-utils:jar:2.0.2-SNAPSHOT, uk.ac.ebi.pride.utilities:pride-utilities:jar:2.0.5-SNAPSHOT, uk.ac.ebi.pride.utilities:pride-protein-inference:jar:0.0.5-SNAPSHOT, com.asperasoft:aspera-
faspmanager:jar:2.7.0.42750: Failure to find uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT in http://pride-proteome.sourceforge.net/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of PRIDE_SourceForge_Maven2_Repository has elapsed or updates are forced
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
        ... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Failure to find uk.ac.ebi.jmzidml:jmzidentml:jar:1.2.3-SNAPSHOT in http://pride-proteome.sourceforge.net/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of PRIDE_SourceForge_Maven2_Repository has e
lapsed or updates are forced
        at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:230)
        at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:204)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:427)
        ... 26 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ypriverol** [comment]
@wolski thanks for using inspector, we upload one of the maven dependencies that is not in public repositories https://github.com/PRIDE-Toolsuite/pride-inspector/tree/master/aspera/lib . you can add this maven dependency by downloading it and using this command:
```maven
mvn install:install-file -Dfile=<path-to-file> -DgroupId=<group-id> \ -DartifactId=<artifact-id> -Dversion=<version> -Dpackaging=<packaging>
```
