### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by thabangh** [PRIDE-Toolsuite/pride-inspector#55]
I downloaded pride-inspector-2.5.1 and tried running it under Linux with Java version 1.6.0_45, but I get the following error:

bash-4.1$ java -jar pride-inspector-2.5.1.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: uk/ac/ebi/pride/toolsuite/gui/PrideInspectorBootstrap : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: uk.ac.ebi.pride.toolsuite.gui.PrideInspectorBootstrap. Program will exit.
bash-4.1$ java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
bash-4.1$ 

Is this a known issue?
Bill Noble

**Comment by julianu** [comment]
Hello Bill,
The PRIDE Inspector needs Java 1.7 now, the README needs obviously updating.
Sorry for the inconvenience.
