### ISSUE TITLE
How to create an executable jar out of the source ?

### ISSUE THREAD

**Issue by epoyraz** [PRIDE-Toolsuite/pride-inspector#56]
i was trying to create a jar out of the PrideInspector source using Eclipse.
How did you create the jar ?

I tried "Export->Runnable Jar" in Eclipse but i get an error executing.
Or is it automatically created by Maven ?

Here is the error :

```
2016-02-11 14:07:27,590 FATAL Desktop - Error occurred during building desktop instance
java.lang.NullPointerException
    at uk.ac.ebi.pride.toolsuite.gui.prop.PropertyManager.loadProps(PropertyManager.java:117)
    at uk.ac.ebi.pride.toolsuite.gui.prop.PropertyManager.loadSystemProps(PropertyManager.java:42)
    at uk.ac.ebi.pride.toolsuite.gui.desktop.DesktopContext.loadSystemProps(DesktopContext.java:228)
    at uk.ac.ebi.pride.toolsuite.gui.PrideInspector.loadProperties(PrideInspector.java:184)
    at uk.ac.ebi.pride.toolsuite.gui.PrideInspector.init(PrideInspector.java:79)
    at uk.ac.ebi.pride.toolsuite.gui.desktop.Desktop$1.run(Desktop.java:46)
[...]
```

**Comment by ypriverol** [comment]
@epoyraz are you using the pom configuration, I guess is the best way. You can use maven to compile and build PRIDE Inspector. See here the documentation in Eclipse: http://www.tutorialspoint.com/maven/maven_eclispe_ide.htm
